# A docker container with pre-processing scripts installed as
# used in the eWaterCycle project for the forecast

FROM ewatercycle/ewatercycle_forecast_base

LABEL maintainer=ewatercycle
LABEL version=0.2

# copy scripts inside docker image
COPY scripts /usr/src/scripts
